# Config Loader - https://github.com/zedseven/config-loader

# Here's where you define the file targets. These are the files you
# have to switch out whenever you want to change to a different configuration.
# Please use absolute file paths.
[targets]
target_name = "/some/file/path.ext"
another_target_name = "/some/other/file/path.ext"

# Here's where each loadout is defined. Include as many files for each loadout
# as you need.
# Each loadout is completely separate from the others. Each one should be a
# complete set of all the files necessary to work.
[[loadouts]]
name = "Some Loadout Name A"
[loadouts.files]
target_name = "/some/file/for/loadout/a.ext"

[[loadouts]]
name = "Some Loadout Name B"
[loadouts.files]
target_name = "/some/file/for/loadout/b.ext"
another_target_name = "/some/other/file/for/loadout/b.ext"
