name: Build

# Run on creation of a pre-release, so the artifacts can be created and later attached for proper release
on:
  release:
    types:
      - prereleased

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - cli
          - gui
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install libgtk-3-dev
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev
        if: matrix.configuration == 'gui' && contains(matrix.os, 'ubuntu')

      - name: restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.configuration }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features ${{ matrix.configuration }}

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: config-loader-${{ matrix.configuration }}-${{ github.event.release.tag_name }} (${{ runner.os }})
          path: target/release/config-loader*
